jobsp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from pjob.views import (skill_location_wise_fresher_jobs, skill_fresher_jobs,
                        skill_location_walkin_jobs, register_using_email, login_user_email,
                        forgot_password, user_activation, user_reg_success,
                        recruiter_profile, jobs_by_location, jobs_by_skill, jobs_by_degree,
                        jobs_by_industry, full_time_jobs, walkin_jobs,
                        city_internship_jobs, internship_jobs, government_jobs,
                        each_company_jobs, job_industries, companies,
                        jobposts_by_date, week_calendar, job_locations, set_password,
                        job_skills, job_detail, year_calendar, calendar_add_event,
                        calendar_event_list, month_calendar, recruiters,
                        user_subscribe, unsubscribe, fresher_jobs_by_skills, process_email, location_fresher_jobs)
from search.views import (skill_auto_search, city_auto_search, custome_search, custom_walkins, search_slugs)
from candidate.views import (applicant_unsubscribe, bounces, assessment_changes,
                             applicant_unsubscribing, applicant_email_unsubscribing,
                             question_view, assessments_questions, alert_subscribe_verification)
from recruiter.views import index
from psite.views import (contact, sitemap, get_out, pages,
                         custom_500, sitemap_xml, users_login, custom_404, auth_return)
from django_blog_it import urls as django_blog_it_urls
from pjob.views import index as job_list
# from django.contrib import admin


urlpatterns = [

    url(r'^(?P<job_title_slug>[a-z0-9-.,*?]+)-(?P<job_id>([0-9])+)/$', job_detail, name="job_detail"),
    url(r'^(?P<skill_name>[-\w]+)-fresher-jobs-in-(?P<city_name>[-\w]+)/$',
        skill_location_wise_fresher_jobs, name="skill_location_wise_fresher_jobs"),
    url(r'^(?P<skill_name>[-\w]+)-fresher-jobs-in-(?P<city_name>[-\w]+)/(?P<page_num>[0-9]+)/$',
        skill_location_wise_fresher_jobs),

    url(r'^internship-jobs-in-(?P<location>[-\w]+)/$', city_internship_jobs, name="city_internship_jobs"),
    url(r'^internship-jobs-in-(?P<location>[-\w]+)/(?P<page_num>[0-9]+)/$', city_internship_jobs),

    url(r'^fresher-jobs-in-(?P<city_name>[-\w]+)/$', location_fresher_jobs, name="location_fresher_jobs"),
    url(r'^fresher-jobs-in-(?P<city_name>[-\w]+)/(?P<page_num>[0-9]+)/$', location_fresher_jobs, name="location_fresher_jobs"),

    url(r'^(?P<skill_name>[-\w]+)-jobs-in-(?P<city_name>[-\w]+)/$', custome_search, name="custome_search"),
    url(r'^(?P<skill_name>[-\w]+)-jobs-in-(?P<city_name>[-\w]+)/(?P<page_num>[0-9]+)/$', custome_search),
    url(r'^(?P<skill_name>[-\w]+)-walkins-in-(?P<city_name>[-\w]+)/$', custom_walkins, name="custom_walkins"),
    url(r'^(?P<skill_name>[-\w]+)-walkins-in-(?P<city_name>[-\w]+)/(?P<page_num>[0-9]+)/$', custom_walkins),
    url(r'^(?P<skill_name>[-\w]+)-fresher-jobs/$', skill_fresher_jobs, name="skill_fresher_jobs"),
    url(r'^(?P<skill_name>[-\w]+)-fresher-jobs/(?P<page_num>[0-9]+)/$', skill_fresher_jobs),
    url(r'^(?P<skill_name>[-\w]+)-walkins/(?P<page_num>[0-9]+)/$', skill_location_walkin_jobs),
    url(r'^(?P<skill_name>[-\w]+)-walkins/$', skill_location_walkin_jobs, name="skill_walkin_jobs"),
    url(r'^walkins-in-(?P<skill_name>[-\w]+)/(?P<page_num>[0-9]+)/$', skill_location_walkin_jobs),
    url(r'^walkins-in-(?P<skill_name>[-\w]+)/$', skill_location_walkin_jobs, name="location_walkin_jobs"),
    url(r'^skill-auto/$', skill_auto_search),
    url(r'^city-auto/$', city_auto_search),
    url(r'^get/search-slugs/$', search_slugs, name="get_search_slugs"),
    # url(r'^admin/', include(admin.site.urls)),  # Here's the typo

    url(r'^search/', include('search.urls', namespace="search")),

    url(r'^applicant-unsubscribe/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$',
        applicant_unsubscribe, name="applicant_unsubscribe"), url(r'^skill-auto/$', skill_auto_search),

    url(r'^unsubscribe_email/(?P<email_type>([a-z0-9-])+)/(?P<message_id>[a-zA-Z0-9_-]+.*?)/$',
        applicant_email_unsubscribing, name="applicant_email_unsubscribing"),
    url(r'^email-unsubscribe/(?P<message_id>[a-zA-Z0-9_-]+.*?)/$',
        applicant_unsubscribing, name="applicant_unsubscribing"),

    url(r'^blog/', include(django_blog_it_urls)),
    url(r'^social/', include('social.urls', namespace="social")),

    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
    url(r'^recruiter/', include('recruiter.urls', namespace="recruiter")),
    url(r'^agency/', include('agency.urls', namespace="agency")),

    url(r'^tellme/', include("tellme.urls")),

    url(r'^post-job/$', index, name='post_job'),
    url(r'^bounces/$', bounces),
    url(r'registration/using_email/$',
        register_using_email, name="register_email"),
    url(r'applicant/login/$', login_user_email, name="login_user"),
    url(r'user/forgot_password/$', forgot_password, name="forgot_password"),
    url(r'^user/set_password/(?P<user_id>[0-9]+)/(?P<passwd>[a-zA-Z0-9]+)/$', set_password, name="set_password"),
    url(r'^user/activation/(?P<user_id>[a-zA-Z0-9]+)/$',
        user_activation, name="user_activation"),
    url(r'^user/reg_success/$', user_reg_success, name="user_reg_success"),
    url(r'^social/user/update/$', user_reg_success, name="social_user"),

    url(r'^recruiters/page/(?P<page_num>[0-9]+)/$', recruiters),
    url(r'^recruiters/(?P<recruiter_name>[a-zA-Z0-9_-]+.*?)/(?P<page_num>[0-9]+)/$',
        recruiter_profile),
    url(r'^recruiters/(?P<recruiter_name>[a-zA-Z0-9_-]+.*?)/$',
        recruiter_profile, name="recruiter_profile"),

    url(r'^(?P<job_type>[-\w]+)-jobs-by-skills/$', fresher_jobs_by_skills, name="fresher_jobs_by_skills"),
    url(r'^(?P<job_type>[-\w]+)-by-location/$', jobs_by_location, name="jobs_by_location"),
    url(r'^jobs-by-skill/$', jobs_by_skill, name="jobs_by_skill"),
    url(r'^jobs-by-industry/$', jobs_by_industry, name="jobs_by_industry"),
    url(r'^jobs-by-degree/$', jobs_by_degree, name="jobs_by_degree"),
    url(r'^full-time-jobs/$', full_time_jobs, name="full_time_jobs"),
    url(r'^full-time-jobs/(?P<page_num>[0-9]+)/$', full_time_jobs),
    url(r'^walkin-jobs/$', walkin_jobs, name="walkin_jobs"),
    url(r'^walkin-jobs/(?P<page_num>[0-9]+)/$', walkin_jobs),

    url(r'^internship-jobs/$', internship_jobs, name="internship_jobs"),
    url(r'^internship-jobs/(?P<page_num>[0-9]+)/$', internship_jobs),

    url(r'^government-jobs/$', government_jobs, name="government_jobs"),
    url(r'^government-jobs/(?P<page_num>[0-9]+)/$', government_jobs),

    url(r'^assessment/question/view/(?P<que_id>[0-9]+)/$', question_view, name="question_view"),
    url(r'^assessment-questions/$', assessments_questions, name="assessments_questions"),
    url(r'^assessment-questions/(?P<page_num>[0-9]+)/$', assessments_questions),
    url(r'^assessment-changes/$', assessment_changes),

    url(r'^sitemap.xml$', sitemap_xml, name="sitemap_xml"),

    url(r'^login/$', users_login, name="users_login"),
    url(r'^contact/$', contact, name="contact"),
    url(
        r'^unsubscribe/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', unsubscribe, name="unsubscribe"),
    url(r'^sitemap/$', sitemap, name="sitemap"),

    url(r'^sitemap/(?P<page_num>[0-9]+)/$', sitemap, name="sitemap"),
    url(r'^logout/$', get_out, name="get_out"),

    url(r'^(?P<company_name>[-\w]+)-job-openings/(?P<page_num>[0-9]+)/$', each_company_jobs),
    url(r'^(?P<company_name>[-\w]+)-job-openings/$', each_company_jobs, name="company_jobs"),

    url(r'^(?P<industry>[-\w]+)-industry-jobs/$', job_industries, name="job_industries"),
    url(r'^(?P<industry>[-\w]+)-industry-jobs/(?P<page_num>[0-9]+)/$', job_industries),
    url(r'^jobs-for-(?P<industry>[-\w]+)-industry/$', job_industries),
    url(r'^jobs-for-(?P<industry>[-\w]+)-industry/(?P<page_num>[0-9]+)/$', job_industries),

    url(r'^(?P<skill>[a-z0-9-.*?]+)-jobs/$', job_skills, name="job_skills"),
    url(r'^(?P<skill>[a-z0-9-.*?]+)-jobs/(?P<page_num>[0-9]+)/$', job_skills),

    url(r'^page/(?P<page_name>([a-z0-9-])+)/$', pages, name="pages"),


    url(r'^companies/(?P<page_num>[0-9]+)/$', companies),
    url(r'companies/$', companies, name='companies'),

    url(r'^', include('candidate.urls', namespace="my")),
    url(r'jobposts/year/(?P<year>\w{0,})/month/(?P<month>\w{0,})/date/(?P<date>\w{0,})/$',
        jobposts_by_date, name="jobposts_by_date"),
    url(r'jobposts/year/(?P<year>\w{0,})/month/(?P<month>\w{0,})/date/(?P<date>\w{0,})/(?P<page_num>[0-9]+)/$',
        jobposts_by_date),


    url(r'calendar/(?P<year>\w{0,})/month/(?P<month>\w{0,})/week/(?P<week>\w{0,})/$',
        week_calendar, name="week_calendar"),

    url(r'tickets/', include('tickets.urls', namespace="tickets")),

    url(r'^jobs-in-(?P<location>[-\w]+)/$', job_locations, name="job_locations"),
    url(r'^jobs-in-(?P<location>[-\w]+)/(?P<page_num>[0-9]+)/$', job_locations),
    url(r'^jobs-for-(?P<skill>[-\w]+)/$', job_skills),


    url(r'calendar/(?P<year>\w{0,})/$', year_calendar, name="year_calendar"),
    url(r'calendar/add/event/$', calendar_add_event, name="calendar_add_event"),
    url(r'calendar/event/list/$', calendar_event_list, name="calendar_event_list"),
    url(r'calendar/(?P<year>\w{0,})/month/(?P<month>\w{0,})/$',
        month_calendar, name="month_calendar"),
    url(r'^oauth2callback/$', auth_return, name='auth_return'),

    url(r'recruiters/$', recruiters, name="recruiters"),

    url(r'^jobs/$', job_list, name="job_list"),

    url(r'^jobs/', include('pjob.urls', namespace="jobs")),
    url(r'user_subscribe/$', user_subscribe, name="user_subscribe"),

    url(r'^(?P<obj_type>([a-z0-9-])+)/verification/(?P<obj_id>[a-zA-Z0-9_-]+.*?)/$',
        alert_subscribe_verification, name="alert_subscribe_verification"),
    url(r'^process-email/$', process_email, name="process_email")

pjob/urls.py
from django.conf.urls import url
from pjob.views import (index, job_apply, user_applied_job,
                        jobs_applied, job_add_event,
                        get_skills)

app_name = "pjob"

urlpatterns = [

    url(r'^$', index, name="index"),
    # url(r'(?P<jp>((\w{0,})-(?P<jid>(\w{0,})))+)(?:\/(?P<uid>[A-Za-z0-9]+))?/$','job_detail'),
    url(r'apply/(?P<job_id>[a-zA-Z0-9_-]+)/$', job_apply, name="job_apply"),
    url(r'applied_for/$', user_applied_job, name="user_applied_job"),
    url(r'applied/$', jobs_applied, name="jobs_applied"),
    url(r'add/event/$', job_add_event, name="job_add_event"),
    url(r'get_skills/$', get_skills, name="get_skills"),
    url(r'^(?P<page_num>[0-9]+)/$', index),
]

templates/mobile/contact-us.html
{% extends 'mobile/base.html' %}
{% load thumbnail %}
{% block block_canonical %}
    <link rel="canonical" href="https://peeljobs.com{{ request.path }}"/>
{% endblock %}

{% block block_title %}
  <title>Contact Us - PeelJobs</title>

  <meta name="description" content="Peeljobs contact us information - Kindly contact us if you have any queries, we'll get back to you shortly."/>

{% endblock %}
{% block stage %}
    <!-- job alert -->

    </section>
    <section id='job_alert_form'>


        <h1>CONTACT US</h1>
        <form name="contactform" id="contactform" method="post">
            <div class='form_group'>
                <div class='label'>First Name<span class="error">*</span></div>
                <div class='input_wrap'>
                    <input type="text" class="input" placeholder="First Name" name="first_name" id="first_name">
                </div>
            </div>
            <!--/ input group -->
            <!-- input group -->
            <div class='form_group'>
                <div class='label'>Last Name</div>
                <div class='input_wrap'>
                    <input type="text" class="input" placeholder="Last Name" name="last_name" id="last_name">
                </div>
            </div>
            <!--/ input group -->
            <!-- input group -->
            <div class='form_group'>
                <div class='label'>Email<span class="error">*</span></div>
                <div class='input_wrap'>
                    <input type="email" class="input" placeholder="Email" name="email" id="email">
                </div>
            </div>
            <!--/ input group -->
            <!-- input group -->
            <div class='form_group'>
                <div class='label'>Mobile Number</div>
                <div class='input_wrap'>
                    <input type="text" class="input" placeholder="Mobile Number" id="mobile" name="mobile">
                </div>
            </div>
            <!--/ input group -->
            <!-- input group -->
            <div class='form_group'>
                <div class='label'>Type of Comment<span class="error">*</span></div>
                <div class='input_wrap'>
                    <select class="input" name="enquery_type" id="enquery_type">
                        <option value="">Select A Comment</option>
                        {% for enquery_type in enquery_types %}
                            <option value="{{ enquery_type.0 }}">{{ enquery_type.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <!--/ input group -->
            <!-- input group -->
            <div class='form_group'>
                <div class='label'>Subject</div>
                <div class='input_wrap'>
                    <input type="text" class="input" placeholder="Subject" name="subject" id="subject">
                </div>
            </div>
            </div>
            <!--/ input group -->
            <!-- input group -->
            <div class='form_group'>
                <div class='label'>Your Comment<span class="error">*</span></div>
                <div class='input_wrap'>
                    <textarea class="input" name="comment" id="comment" placeholder="Comment"></textarea>
                    <input type="hidden" class="input" placeholder="Email" name="user_authenticated"
                           id="user_authenticated"
                           value="{% if not request.user.is_authenticated %}False{% else %}True{% endif %}">
                </div>
            </div>
            <!--/ input group -->
            <!-- input group -->
            <div  class="form-group col-xs-12 form-field wow fadeInUp animated">
                      
                      <div class="button_div">
                        <div class="g-recaptcha" data-sitekey="6LdZcgkTAAAAAD7-f9vAtRfoTsu1K7bnPfyB4i88"></div>
                      </div>
                    </div>
            <!--/ input group -->

            <!-- button row -->
            <div class="button_row">
                <button type="submit" class="button reset_filter"><span class='pj-reset i'></span>Submit</button>
                <button type="button" class="button submit cancelbutton"><span class='pj-checkbox i'></span>Cancel
                </button>

            </div>
            <!--/ button row -->
        </form>
        <!--/ form -->
        <div class="row mt content-page about-us address_block">
            <!-- content starts here -->
            <div class="content more">
                <div class="contact-details">
                    <ul>
                        <li class="clist-head"> Contact Us :-</li>
                        <li><i class="fa fa-envelope"></i> Email:<a href="#"> support@peeljobs.com</a></li>
                        <li><i class="fa fa-mobile"></i> Ph No:<a href="#"> 850 009 9499 </a></li>
                    </ul>
                    <!--  <ul>
                       <li class="clist-head">  Address :-</li>
                       <li><i class="fa fa-building"></i>HIG499, Viswa sai dham apartment, <br>behind anupama hospital,<br> 6th phase KPHB, <br>Hyderabad - 72</li>
                     </ul>
                     <ul>
                       <li class="clist-head">  Business Hours :-</li>
                       <li> <i class="fa fa-clock-o"></i> Monday - Friday : 10:00 - 19:00 </li>
                       <li> <i class="fa fa-clock-o"></i> Saturday : 10:00 - 19:00 </li>
                     </ul> -->
                </div>
            </div>
            <!-- content ends here -->
            <!-- Tab panes -->
        </div>

    </section>
    <!--/ job alert -->
{% endblock %}
{% block 'extra_js' %}
          <script src='https://www.google.com/recaptcha/api.js'></script>

    <script type="text/javascript">
        $(".cancelbutton").click(function (e) {
            window.location = "{% url 'jobs:index'%}";
        });


        $("form#contactform").submit(function (e) {
            e.preventDefault();
             $.post(".", $("form#contactform").serialize(), function(data) {
                if (data.error) {
          open_dialog("Some content Missing", 'Error!')
          $('p.hint').remove();
          for (var key in data.response) {
            $('#' + key).after('<p class="hint">' + data.response[key] + '</p>');
          }
        } else {
          open_dialog_with_url("Your request has been registered, we will reach you soon", 'Success!', '/')
        }
      }, 'json');
        });

        $("select.cities").select2({placeholder: "Select the city", maximumSelectionSize: 20});

        $("select.skills").select2({placeholder: "Select the skill", maximumSelectionSize: 20});
        $("select.indutry").select2({placeholder: "Select the  industry", maximumSelectionSize: 20});

    </script>

{% endblock %}

templates/mobile/faq.html
{% extends 'mobile/base.html'%}
{% load page_tags %}
{% load thumbnail %}
{% block block_title %}
  <title>FAQ - PeelJobs</title>
  <meta name="description" content="Frequently asked questions for candidates to find solutions for all their queries during job search."/>

{% endblock %}

{% block stage %}
<div class="static_pages_from_wrap">
  <!-- SEARCH PART -->
  <section id='content_wrap_list'>
    <div class="container">
      <div class="row mt content-page">
        <!-- content starts here -->
        <h3 class="title">FREQUENTLY ASKED QUESTIONS</h3>
        <div class="content">
          <p class="sub-head">CANDIDATE : </p>
          <p class="adv-head"><b><span class="que">Q : </span>About peeljobs.com ?</b><br>
            <span class="ans">A : </span>Peeljobs.com is a job portal site where you can find your suitable jobs easily and fastly.
          </p>
          <p class="adv-head"><b><span class="que">Q : </span>How can i search for jobs ?</b><br>
            <span class="ans">A : </span>whenever jobs are available, peeljobs.com posted that jobs on various social sites like facebook, linked IN, twitter etc. From there you can directly apply to jobs. No need to register, no need to pay any registration fee.
            .
          </p>
          <p class="adv-head"><b><span class="que">Q : </span>How to apply for jobs?</b><br>
            <span class="ans">A : </span>According to your requirement you can direct apply jobs from social sites. you can see similar jobs also, if you find relevant you can apply as you want.
          </p>
          <p class="adv-head"><b><span class="que">Q : </span>How do i know i am being selected/shortlisted for a job ?</b><br>
            <span class="ans">A : </span> If you are selected, you will get a notification via email or given contact number.
          </p>
          <p class="adv-head"><b><span class="que">Q : </span> How do i submit my resume  ?</b><br>
            <span class="ans">A : </span>When completing the details  of the online application form, you will be asked to attach your CV, so make sure you have it ready.
          </p>
          <p class="adv-head"><b><span class="que">Q : </span>Can i apply more than one job ?</b><br>
            <span class="ans">A : </span>If you meet qualifications and experience necessary for that position then you may apply for more than one vacancy by completing the application requirements.
            Everyday new and active jobs are posted.
          </p>
          <p class="adv-head"><b><span class="que">Q : </span>If i do not find a suitable vacancy, what can i do ?</b><br>
            <span class="ans">A : </span>If you do not find a suitable job, we encourage you to see job details every day.
          </p>
        </div>
        <!-- content ends here -->
        <!-- Tab panes -->
      </div>
    </div>
  </section>
  <!-- content of job page -->
</div>
{% endblock %}

templates/mobile/sitemap.html
{% extends 'mobile/base.html'%}
{% load thumbnail %}
{% load page_tags %}
{% block block_title %}
  <title>Sitemap {{current_page}} - PeelJobs</title>

  <meta name="description" content="Peeljobs sitemap {{current_page}} to browse all the jobs by location, skills, industry etc."/>

{% endblock %}

{% block stage %}
<div class="static_pages_from_wrap">
  <!-- SEARCH PART -->
  <section id='content_wrap_list'>
    <div class="container">
      <div class="row mt content-page">
        <!-- content starts here -->
          <div class="col-md-12 col-sm-12 sitemap">
        <ul>
            {% get_all_skills as skills %}
            {% get_locations as locations %}
            {% if current_page == 1  %}
            <li><a href='https://peeljobs.com/'>Home</a></li>
            <li><a href="{% url 'pages' 'about-us' %}">About</a></li>
            <li><a href="{% url 'pages' 'terms-conditions' %}">Terms & Conditions</a></li>
            <li><a href="{% url 'pages' 'privacy-policy' %}">Privacy Policy</a></li>
            <li><a href="{% url 'contact' %}">Contact Us</a></li>
            <li><a href="{% url 'pages' 'recruiter-faq' %}">Recruiter FAQ</a></li>
            <li><a href="{% url 'pages' 'faq' %}">Job Seeker FAQ</a></li>
            <li><a href="{% url 'jobs:index' %}">View All Jobs</a></li>

            <li class="sitemap-parent"><a href="{% url 'jobs_by_location' 'jobs' %}">Locations</a></li>
              {% for location in locations %}
               <li class="sitemap-child"><a href="{% url 'job_locations' location.slug %}">Jobs in {{ location.name }}</a></li>
            {% endfor %}
          {% elif current_page == 2  %}
          <li class="sitemap-parent"><a href="{% url 'jobs_by_skill' %}">Skills</a></li>
              {% for skill in skills %}
               <li class="sitemap-child"><a href="{% url 'job_skills' skill.slug %}">Jobs For {{ skill.name }}</a></li>
            {% endfor %}
          {% elif current_page == 3  %}
          <li class="sitemap-parent"><a>Jobs by Educations</a></li>
            {% for edu in educations %}
               <li class="sitemap-child"><a href="{% url 'job_skills' edu.slug %}">{{ edu.name }} Jobs</a></li>
            {% endfor %}
          <li class="sitemap-parent"><a href="">State Wise Jobs</a></li>
            {% for state in states %}
              <li class="sitemap-child"><a href="{% url 'job_locations' state.slug %}">Jobs in {{ state.name }}</a></li>
            {% endfor %}
            {% for state in states %}
              <li class="sitemap-child"><a href="{% url 'location_walkin_jobs' state.slug %}">Walkins in {{ state.name }}</a></li>
            {% endfor %}
            {% for state in states %}
              <li class="sitemap-child"><a href="{% url 'location_fresher_jobs' state.slug %}">Fresher Jobs in {{ state.name }}</a></li>
            {% endfor %}
          {% elif current_page == 4  %}
          <li class="sitemap-parent"><a>Walkins by Skills and Locations</a></li>
          {% for city in locations %}
                {% for skill in skills %}
                 <li class="sitemap-child"><a href="{% url 'custom_walkins' skill.slug city.slug %}">{{ skill.name }} Walk-ins in {{ city.name }}</a></li>
              {% endfor %}
            {% endfor %}
          {% elif current_page == 5  %}
          <li class="sitemap-parent"><a href="{% url 'jobs_by_location' 'fresher-jobs' %}">Fresher Jobs by Locations</a></li>
            {% for location in locations %}
               <li class="sitemap-child"><a href="{% url 'location_fresher_jobs' location.slug %}">Fresher Jobs in {{ location.name }}</a></li>
            {% endfor %}

          {% elif current_page == 6  %}
          <li class="sitemap-parent"><a href="{% url 'jobs_by_industry' %}">Industry</a></li>
            {% get_all_industries as industries %}
              {% for industry in industries %}
               <li class="sitemap-child"><a href="{% url 'job_industries' industry.slug %}">Jobs For {{ industry.name }}</a></li>
            {% endfor %}
          {% elif current_page == 7  %}
            <li class="sitemap-parent"><a href="{% url 'internship_jobs' %}">Internships</a></li>
            {%get_internships as all_internship_jobs%}
              {% for city in all_internship_jobs %}
                <li class="sitemap-child"><a href="{% url 'city_internship_jobs' city.slug  %}" title="{{ job.title}}">Internship in {{ city.name }}</a></li>
              {% endfor %}
          {% else %}
            {% if jobposts|get_object_list_type:"full-time" %}
               <li class="sitemap-parent"><a href="{% url 'full_time_jobs' %}">Full Time Jobs</a></li>
            {% endif %}
            {% for post in jobposts %}
              {% if post|get_job_type == 'full-time' %}
                 <li class="sitemap-child"><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></li>
              {% endif %}
            {% endfor %}


            {% if jobposts|get_object_list_type:"internship" %}
              <li class="sitemap-parent"><a href="{% url 'internship_jobs' %}">Internship Jobs</a></li>
            {% endif %}
            {% for post in jobposts %}
              {% if post|get_job_type == 'internship' %}
                 <li class="sitemap-child"><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></li>
              {% endif %}
            {% endfor %}

            {% if jobposts|get_object_list_type:"walk-in" %}
               <li class="sitemap-parent"><a href="{% url 'walkin_jobs' %}">Walk-in's</a></li>
            {% endif %}
            {% for post in jobposts %}
              {% if post|get_job_type == 'walk-in' %}
                 <li class="sitemap-child"><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></li>
              {% endif %}
            {% endfor %}

            {% if jobposts|get_object_list_type:"government" %}
               <li class="sitemap-parent"><a href="{% url 'government_jobs' %}">Government Jobs</a></li>
            {% endif %}
            {% for post in jobposts %}
              {% if post|get_job_type == 'government' %}
                 <li class="sitemap-child"><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></li>
              {% endif %}
            {% endfor %}
          {% endif %}
            <br>
        {% get_page current_page last_page|add:'6' as pages %}
        {% if current_page > 6 %}
                  <li><a href="/sitemap/"> First Site map</a></li>
        {% endif %}
        {% for s in pages %}
          {% if current_page == s %}
          {% else %}
          <li><a href="/sitemap/{{ s }}/">Site map{{s}}</a></li>
          {% endif %}
        {% endfor %}
        {% if current_page <  last_page|add:'-6' %}
          <li><a href="/sitemap/{{last_page|add:'6'}}/"> Last Site map</a></li>
        {% endif %}
        </ul>
      </div>
      </div>
    </div>
  </section>
  <!-- content of job page -->
</div>
{% endblock %}
{% block 'extra_js' %}
<script type="text/javascript">
$(document).ready(function(){
$('ul li').click(function(e){
  e.preventDefault();
  window.location = $(this).find('a').attr('href')
});
});
</script>
{% endblock %}